Fix SnakeYAML version conflict with Axway by shading dependencies
Added relocations in maven-shade-plugin for:
- org.yaml.snakeyaml -> shaded.org.yaml.snakeyaml (fixes NoSuchMethodError)
- io.swagger -> shaded.io.swagger
- org.apache.commons -> shaded.org.apache.commons
- com.google -> shaded.com.google (Guava)

These relocations prevent classpath conflicts with Axway's built-in
versions of these libraries.