Add more shade relocations to fix Axway class conflicts
Added relocations for:
- com.atlassian.oai (the validator itself)
- com.networknt (JSON Schema validator)
- com.github.fge (JSON Schema library)
- com.ethlo (time library)
- javax.validation (validation API)
- org.joda (Joda Time)

This fixes NoClassDefFoundError for Nullable class when
running in Axway environment due to conflicting library versions.